# Generated by Django 5.0.1 on 2024-01-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sum_2num', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number1', models.FloatField()),
                ('number2', models.FloatField()),
                ('result', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SumResult',
        ),
    ]
