# Generated by Django 5.0.1 on 2024-01-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sum_2num', '0002_calculation_delete_sumresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.IntegerField()),
                ('num2', models.IntegerField()),
                ('result', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Calculation',
        ),
    ]
