# Generated by Django 5.0.1 on 2024-01-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sum_2num', '0006_rename_number_numbers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Numbers',
            new_name='AdditionResult',
        ),
    ]
