# Generated by Django 5.0.1 on 2024-01-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sum_2num', '0007_rename_numbers_additionresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.IntegerField()),
                ('num2', models.IntegerField()),
                ('result', models.IntegerField()),
            ],
        ),
    ]
